import * as React from "react";
import * as Types from "../webflow_modules/types";

declare function NavBar2(props: {
  brandLogoBrandLogoVisibility?: Types.Visibility.VisibilityConditions;
  brandLogoImage?: Types.Asset.Image;
  brandLogoImageAltText?: Types.Basic.AltText;
  buttonButtonLink?: Types.Basic.Link;
  buttonButtonText?: React.ReactNode;
  buttonButtonVisibility?: Types.Visibility.VisibilityConditions;
  colorNavCardSlot?: React.ReactNode;
  colorNavCardSlot2?: React.ReactNode;
  colorNavCardSlot3?: React.ReactNode;
  colorNavCardSlot4?: React.ReactNode;
  m2Card1HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m2Card1HeadlineText?: React.ReactNode;
  m2Card1Icon?: Types.Asset.Image;
  m2Card1IconAltText?: Types.Basic.AltText;
  m2Card1Image?: Types.Asset.Image;
  m2Card1ImageAltText?: Types.Basic.AltText;
  m2Card1Link?: Types.Basic.Link;
  m2Card1LinkText?: React.ReactNode;
  m2Card1Paragraph?: React.ReactNode;
  m2Card2HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m2Card2HeadlineText?: React.ReactNode;
  m2Card2Icon?: Types.Asset.Image;
  m2Card2IconAltText?: Types.Basic.AltText;
  m2Card2Image?: Types.Asset.Image;
  m2Card2ImageAltText?: Types.Basic.AltText;
  m2Card2Link?: Types.Basic.Link;
  m2Card2LinkText?: React.ReactNode;
  m2Card2Paragraph?: React.ReactNode;
  m2Card3HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m2Card3HeadlineText?: React.ReactNode;
  m2Card3Icon?: Types.Asset.Image;
  m2Card3IconAltText?: Types.Basic.AltText;
  m2Card3Image?: Types.Asset.Image;
  m2Card3ImageAltText?: Types.Basic.AltText;
  m2Card3Link2?: Types.Basic.Link;
  m2Card3LinkText?: React.ReactNode;
  m2Card3Paragraph?: React.ReactNode;
  m2Card4HeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m2Card4HeadlineText?: React.ReactNode;
  m2Card4Icon?: Types.Asset.Image;
  m2Card4IconAltText?: Types.Basic.AltText;
  m2Card4Image?: Types.Asset.Image;
  m2Card4ImageAltText?: Types.Basic.AltText;
  m2Card4Link?: Types.Basic.Link;
  m2Card4LinkText?: React.ReactNode;
  m2Card4Paragraph?: React.ReactNode;
  menuDropdown1MenuDropdownVisibility?: Types.Visibility.VisibilityConditions;
  menuDropdown2MenuDropdownVisibility?: Types.Visibility.VisibilityConditions;
  menuLink1MenuLink?: Types.Basic.Link;
  menuLink1MenuLinkText?: React.ReactNode;
  menuLink1MenuLinkVisibility?: Types.Visibility.VisibilityConditions;
  menuLink2MenuLink?: Types.Basic.Link;
  menuLink2MenuLinkText?: React.ReactNode;
  menuLink2MenuLinkVisibility?: Types.Visibility.VisibilityConditions;
  menuLink3MenuLink?: Types.Basic.Link;
  menuLink3MenuLinkText?: React.ReactNode;
  menuLink3MenuLinkVisibility?: Types.Visibility.VisibilityConditions;
  menuLink4MenuLink?: Types.Basic.Link;
  menuLink4MenuLinkText?: React.ReactNode;
  menuLink4MenuLinkVisibility?: Types.Visibility.VisibilityConditions;
  menuLink5MenuLink?: Types.Basic.Link;
  menuLink5MenuLinkText?: React.ReactNode;
  menuLink5MenuLinkVisibility?: Types.Visibility.VisibilityConditions;
  optionsColorCardColor?: unknown;
  optionsNavBarColor?: "Light" | "Dark";
  settingsNavBarVisibility?: Types.Visibility.VisibilityConditions;
  whiteNavCardSlot?: React.ReactNode;
  whiteNavCardSlot2?: React.ReactNode;
  whiteNavCardSlot3?: React.ReactNode;
  whiteNavCardSlot4?: React.ReactNode;
}): React.JSX.Element;
