import * as React from "react";
import * as Types from "../webflow_modules/types";

declare function PageNav(props: {
  contactLinkButtonLink?: Types.Basic.Link;
  contactLinkButtonSize?:
    | "Big Left Align"
    | "Big Center Align"
    | "Regular Left Align"
    | "Regular Center Align"
    | "Small Left Align"
    | "Small Center Align"
    | "Responsive Size";
  contactLinkButtonText?: React.ReactNode;
  contactLinkButtonVisibility?: Types.Visibility.VisibilityConditions;
  contactLinkIcon?: Types.Asset.Image;
  contactLinkIconAltText?: Types.Basic.AltText;
  contactLinkUnderlineVisibility?: Types.Visibility.VisibilityConditions;
  headlineMenuNavHeadline?: React.ReactNode;
  headlineMenuNavHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m3Submenu1Icon?: Types.Asset.Image;
  m3Submenu1IconAltText?: Types.Basic.AltText;
  m3Submenu1IconVisibility?: Types.Visibility.VisibilityConditions;
  m3Submenu1SubmenuHeadline?: React.ReactNode;
  m3Submenu1SubmenuHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m3Submenu1SubmenuParagraph?: React.ReactNode;
  m3Submenu1SubmenuTag?: React.ReactNode;
  m3Submenu2Icon?: Types.Asset.Image;
  m3Submenu2IconAltText?: Types.Basic.AltText;
  m3Submenu2IconVisibility?: Types.Visibility.VisibilityConditions;
  m3Submenu2SubmenuHeadline?: React.ReactNode;
  m3Submenu2SubmenuHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m3Submenu2SubmenuParagraph?: React.ReactNode;
  m3Submenu2SubmenuTag?: React.ReactNode;
  m3Submenu3Icon?: Types.Asset.Image;
  m3Submenu3IconAltText?: Types.Basic.AltText;
  m3Submenu3IconVisibility?: Types.Visibility.VisibilityConditions;
  m3Submenu3SubmenuHeadline?: React.ReactNode;
  m3Submenu3SubmenuHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m3Submenu3SubmenuParagraph?: React.ReactNode;
  m3Submenu3SubmenuTag?: React.ReactNode;
  m3Submenu4Icon?: Types.Asset.Image;
  m3Submenu4IconAltText?: Types.Basic.AltText;
  m3Submenu4IconVisibility?: Types.Visibility.VisibilityConditions;
  m3Submenu4SubmenuHeadline?: React.ReactNode;
  m3Submenu4SubmenuHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m3Submenu4SubmenuParagraph?: React.ReactNode;
  m3Submenu4SubmenuTag?: React.ReactNode;
  m4Submenu1Icon?: Types.Asset.Image;
  m4Submenu1IconAltText?: Types.Basic.AltText;
  m4Submenu1IconVisibility?: Types.Visibility.VisibilityConditions;
  m4Submenu1Image?: Types.Asset.Image;
  m4Submenu1ImageAltText?: Types.Basic.AltText;
  m4Submenu1ImageVisibility?: Types.Visibility.VisibilityConditions;
  m4Submenu1SubmenuHeadline?: React.ReactNode;
  m4Submenu1SubmenuHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m4Submenu1SubmenuParagraph?: React.ReactNode;
  m4Submenu1SubmenuTag?: React.ReactNode;
  m4Submenu2Icon?: Types.Asset.Image;
  m4Submenu2IconAltText?: Types.Basic.AltText;
  m4Submenu2IconVisibility?: Types.Visibility.VisibilityConditions;
  m4Submenu2Image?: Types.Asset.Image;
  m4Submenu2ImageAltText?: Types.Basic.AltText;
  m4Submenu2ImageVisibility?: Types.Visibility.VisibilityConditions;
  m4Submenu2SubmenuHeadline?: React.ReactNode;
  m4Submenu2SubmenuHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m4Submenu2SubmenuParagraph?: React.ReactNode;
  m4Submenu2SubmenuTag?: React.ReactNode;
  m4Submenu3Icon?: Types.Asset.Image;
  m4Submenu3IconAltText?: Types.Basic.AltText;
  m4Submenu3IconVisibility?: Types.Visibility.VisibilityConditions;
  m4Submenu3Image?: Types.Asset.Image;
  m4Submenu3ImageAltText?: Types.Basic.AltText;
  m4Submenu3ImageVisibility?: Types.Visibility.VisibilityConditions;
  m4Submenu3SubmenuHeadline?: React.ReactNode;
  m4Submenu3SubmenuHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m4Submenu3SubmenuParagraph?: React.ReactNode;
  m4Submenu3SubmenuTag?: React.ReactNode;
  m4Submenu4Icon?: Types.Asset.Image;
  m4Submenu4IconAltText?: Types.Basic.AltText;
  m4Submenu4IconVisibility?: Types.Visibility.VisibilityConditions;
  m4Submenu4Image?: Types.Asset.Image;
  m4Submenu4ImageAltText?: Types.Basic.AltText;
  m4Submenu4ImageVisibility?: Types.Visibility.VisibilityConditions;
  m4Submenu4SubmenuHeadline?: React.ReactNode;
  m4Submenu4SubmenuHeadlineTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  m4Submenu4SubmenuParagraph?: React.ReactNode;
  m4Submenu4SubmenuTag?: React.ReactNode;
  menuLink1MenuLink?: Types.Basic.Link;
  menuLink1MenuText?: React.ReactNode;
  menuLink2MeetTheRebels?: Types.Basic.Link;
  menuLink2MenuText?: React.ReactNode;
  menuLink3MenuLink3Visibility?: Types.Visibility.VisibilityConditions;
  menuLink3MenuText?: React.ReactNode;
  menuLink3SubmenuLink1?: Types.Basic.Link;
  menuLink3SubmenuLink2?: Types.Basic.Link;
  menuLink3SubmenuLink3?: Types.Basic.Link;
  menuLink3SubmenuLink4?: Types.Basic.Link;
  menuLink4MenuLink4Visibility?: Types.Visibility.VisibilityConditions;
  menuLink4MenuText?: React.ReactNode;
  menuLink4SubmenuLink1?: Types.Basic.Link;
  menuLink4SubmenuLink2?: Types.Basic.Link;
  menuLink4SubmenuLink3?: Types.Basic.Link;
  menuLink4SubmenuLink4?: Types.Basic.Link;
  menuLink5MenuLink?: Types.Basic.Link;
  menuLink5MenuLink5Visibility?: Types.Visibility.VisibilityConditions;
  menuLink5MenuLinkText?: React.ReactNode;
  menuLink6MenuLink?: Types.Basic.Link;
  menuLink6MenuLink6Visibility?: Types.Visibility.VisibilityConditions;
  menuLink6MenuLinkText?: React.ReactNode;
  menuLink7MenuLink?: Types.Basic.Link;
  menuLink7MenuLink7Visibility?: Types.Visibility.VisibilityConditions;
  menuLink7MenuLinkText?: React.ReactNode;
  settingsIconAltText?: Types.Basic.AltText;
  settingsMenuIconVisibility?: Types.Visibility.VisibilityConditions;
  settingsMenuOpenIcon?: Types.Asset.Image;
  settingsMenuText?: React.ReactNode;
  settingsMenuTextVisibility?: Types.Visibility.VisibilityConditions;
  settingsNavBarId?: string;
  settingsNavBarMainText?: React.ReactNode;
  settingsNavBarVisibility?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
