/* eslint-disable @typescript-eslint/no-empty-interface */
// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
  LIKES_VIEWS_KV: KVNamespace;
}
