import * as React from "react";
import * as Types from "./types";

declare function Footer(
    props: {
        as?: React.ElementType;
        settingsFooterVisibility?: Types.Visibility.VisibilityConditions;
        settingsFooterId?: Types.Basic.IdTextInput;
        brandBrandLogo?: Types.Asset.Image;
        brandBrandLogoAltText?: Types.Basic.AltText;
        brandBrandTaglineVisibility?: Types.Visibility.VisibilityConditions;
        brandBrandTaglineText?: React.ReactNode;
        newsletterNewsletterSignupText?: React.ReactNode;
        newsletterNewsletterSignupCtaText?: Types.Builtin.Text;
        newsletterPrivacyPolicy1Visibility?: Types.Visibility.VisibilityConditions;
        newsletterPrivacyPolicy1Text?: React.ReactNode;
        newsletterPrivacyPolicyLinkVisibility?: Types.Visibility.VisibilityConditions;
        newsletterPrivacyPolicyLink?: Types.Basic.Link;
        newsletterPrivacyPolicy2Visibility?: Types.Visibility.VisibilityConditions;
        newsletterPrivacyPolicy2Text?: React.ReactNode;
        copyrightCopyrightText?: React.ReactNode;
        policyLinksPrivacyPolicyLinkVisibility?: Types.Visibility.VisibilityConditions;
        policyLinksPrivacyPolicyLink?: Types.Basic.Link;
        policyLinksPrivacyPolicyLinkText?: React.ReactNode;
        policyLinksTermsOfServiceLinkVisibility?: Types.Visibility.VisibilityConditions;
        policyLinksTermsOfServiceLink?: Types.Basic.Link;
        policyLinksTermsOfServiceLinkText?: React.ReactNode;
        policyLinksPrivacyPolicyText?: React.ReactNode;
        policyLinksCookiesLinkTextVisibility?: Types.Visibility.VisibilityConditions;
        policyLinksCookieLink?: Types.Basic.Link;
        policyLinksCookiesLinkText?: React.ReactNode;
        contactContactHeadlineVisibility?: Types.Visibility.VisibilityConditions;
        contactContactHeadlineText?: React.ReactNode;
        contactPhoneNumberVisibility?: Types.Visibility.VisibilityConditions;
        contactPhoneNumberText?: React.ReactNode;
        contactEmailAddressVisibility?: Types.Visibility.VisibilityConditions;
        contactEmailAddressText?: React.ReactNode;
        contactWebsiteAddressVisibility?: Types.Visibility.VisibilityConditions;
        contactWebsiteAddressText?: React.ReactNode;
        addressAddressHeadlineVisibility?: Types.Visibility.VisibilityConditions;
        addressAddressHeadlineText?: React.ReactNode;
        addressAddressLine1Visibility?: Types.Visibility.VisibilityConditions;
        addressAddressLine1Text?: React.ReactNode;
        addressAddressLine2Visibility?: Types.Visibility.VisibilityConditions;
        addressAddressLine2Text?: React.ReactNode;
        addressCityStateZipVisibility?: Types.Visibility.VisibilityConditions;
        addressCityStateZipText?: React.ReactNode;
        socialsSocialsHeadlineVisibility?: Types.Visibility.VisibilityConditions;
        socialsSocialsHeadlineText?: React.ReactNode;
        socialButton1SocialButtonVisibility?: Types.Visibility.VisibilityConditions;
        socialButton1IconSize?: "2x2" | "3x3" | "4x4";
        socialButton1SocialPlatform?: "Base" | "Instagram" | "Instagram Outline" | "Linkedin" | "LinkedIn Outline" | "Facebook" | "Facebook Outline" | "X" | "X Outline" | "Blog" | "Blog Outline" | "Github" | "Google" | "Google Drive";
        socialButton2SocialButtonVisibility?: Types.Visibility.VisibilityConditions;
        socialButton2SocialPlatform?: "Base" | "Instagram" | "Instagram Outline" | "Linkedin" | "LinkedIn Outline" | "Facebook" | "Facebook Outline" | "X" | "X Outline" | "Blog" | "Blog Outline" | "Github" | "Google" | "Google Drive";
        socialButton3SocialButtonVisibility?: Types.Visibility.VisibilityConditions;
        socialButton3SocialPlatform?: "Base" | "Instagram" | "Instagram Outline" | "Linkedin" | "LinkedIn Outline" | "Facebook" | "Facebook Outline" | "X" | "X Outline" | "Blog" | "Blog Outline" | "Github" | "Google" | "Google Drive";
        socialButton3IconSize?: "2x2" | "3x3" | "4x4";
        socialButton4SocialButtonVisibility?: Types.Visibility.VisibilityConditions;
        socialButton4SocialPlatform?: "Base" | "Instagram" | "Instagram Outline" | "Linkedin" | "LinkedIn Outline" | "Facebook" | "Facebook Outline" | "X" | "X Outline" | "Blog" | "Blog Outline" | "Github" | "Google" | "Google Drive";
        socialButton4IconSize?: "2x2" | "3x3" | "4x4";
        socialButton5SocialButtonVisibility?: Types.Visibility.VisibilityConditions;
        socialButton5SocialPlatform?: "Base" | "Instagram" | "Instagram Outline" | "Linkedin" | "LinkedIn Outline" | "Facebook" | "Facebook Outline" | "X" | "X Outline" | "Blog" | "Blog Outline" | "Github" | "Google" | "Google Drive";
        socialButton5IconSize?: "2x2" | "3x3" | "4x4";
        socialButton5SocialButtonLink?: Types.Basic.Link;
        socialButton3SocialButtonLink?: Types.Basic.Link;
        socialButton1SocialButtonLink?: Types.Basic.Link;
        socialButton2SocialButtonLink?: Types.Basic.Link;
        socialButton4SocialButtonLink?: Types.Basic.Link;
        socialButton2IconSize?: "2x2" | "3x3" | "4x4";
        variant?: "Light" | "Outline Light" | "Dark" | "Outline Dark";
    }
): React.JSX.Element